language: node_js

node_js:
  - 12

before_script:
  - yarn install

cache: yarn

jobs:
  include:
    - name: "Deploy to Chromatic"
      fork=false # forks dont build
      #script: yarn chromatic --project-token=84svyadsh4w
      if: (type = push AND branch = main)
      script: yarn chromatic --project-token=84svyadsh4w