language: node_js
os: linux
dist: xenial

node_js:
  - 12

before_script:
  - yarn install

cache: yarn
branches:
  only: main
jobs:
  include:
   - name: 'Chromatic Deployment'
     if: (type = push OR ${TRAVIS_PULL_REQUEST_SLUG} != ${TRAVIS_REPO_SLUG} )
     #script: yarn chromatic --project-token=84svyadsh4w --exit-zero-on-changes
     script: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes